// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/lapumk/inspenjualan": {
            "post": {
                "description": "get data penjualan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lapak-UMKM"
                ],
                "summary": "insert data penjualan.",
                "parameters": [
                    {
                        "description": "Payload Body [RAW]",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Penjualan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Penjualan"
                        }
                    }
                }
            }
        },
        "/lapumk/pengeluaran/{namaproduk}": {
            "get": {
                "description": "get data pengeluaran.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lapak-UMKM"
                ],
                "summary": "Mengambil data Pengeluaran (single).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Masukan namaproduk",
                        "name": "namaproduk",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Pengeluaran"
                        }
                    }
                }
            }
        },
        "/lapumk/penjualan/{namapenjualan}": {
            "get": {
                "description": "get data Penjualan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lapak-UMKM"
                ],
                "summary": "Mengambil data Penjualan (single).",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Masukan namapenjualan",
                        "name": "namapenjualan",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Penjualan"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Pengeluaran": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "string"
                },
                "jumlah": {
                    "type": "integer"
                },
                "namapengeluaran": {
                    "type": "string"
                },
                "tanggal": {
                    "type": "string"
                }
            }
        },
        "model.Penjualan": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "jumlahpenjualan": {
                    "type": "string"
                },
                "namaproduk": {
                    "type": "string"
                },
                "tanggaldatamasuk": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "Lapak-UMK.herokuapp.com",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "LAPAK-UMK OPEN API PROTOTYPE",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
